spring.application.name=Spelunker

#### PORT CONFIG ####
server.port=8085

#### MYSQL DATASOURCE ####
spring.datasource.url=jdbc:mysql://localhost:3306/cavesdb
spring.datasource.username=spelunker
spring.datasource.password=spelunker
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jmx.default-domain=Spelunker