spring.application.name=DirtyDrinks

#### PORT CONFIG ####
server.port=8083

#### MYSQL DATASOURCE ####
spring.datasource.url=jdbc:mysql://localhost:3306/dirtysodadb
spring.datasource.username=sodadrinker
spring.datasource.password=sodadrinker
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jmx.default-domain=DirtyDrinks